#! /bin/bash

rosparam set user_sim_time true
echo "enter bag in rosbags dir:"
read bagpath

#spawn new terminal for 'rosrun rviz rviz'
xdotool key ctrl+shift+n
echo "we are in, but lets keep it quiet"

rosbag play -l $(pwd)/rosbags/$bagpath

echo got your rosbags/$bagpath





